# Base configuration
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
markdown: kramdown
highlighter: rouge

collections:
  pages:
    output: true
    permalink: /:path/

# Title
name: ASU Labs Theme
subtitle: A theme for faculty lab sites, sponsored by ASU Engineering.

# When using this template with a project page set the baseurl to '/project-name'
# For user/organization pages set this to an empty string
# When working locally use jekyll serve --baseurl '' so that you can view everything at localhost:4000
# See http://jekyllrb.com/docs/github-pages/ for more info
#baseurl: ''
baseurl: "/asu-labs-theme"

# Author/Organization info to be displayed in the templates
author:
  name: Steve Ryan, ASU Engineering
  url:

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl:
logoalt:

# Navigation
# List links that should appear in the site sidebar here
navigation:
  - text: Home
    url: ./
    internal: true
  - text: Quick Start Guide
    url: quick-start/
    internal: true
  - text: Connected Content
    url: connections/
    internal: true
  - text: People
    url: people/
    internal: true
  - text: Directory Page
    url: directory/
    internal: true
  - text: Research Projects
    url: research/
    internal: true
  - text: Research Themes
    url: research-theme/
    internal: true
  - text: Publications
    url: publications/
    internal: true
  - text: Labels and Categories
    url: categories/
    internal: true
  - text: Customizing the Menu
    url: sidebar/
    internal: true
  - text: About this theme
    url: about/
    internal: true

# Repo list
# List repos that you would like to appear on the homepage here
repos:
  - name: asu-labs-theme
    description: A theme for WordPress to build and organize small group websites. Ideal for engineering "lab" groups on campus.
    url: https://github.com/asuengineering/asu-labs-theme

# Offline caching
offline_cache: false
cache_name: DOCter-v1.1
